kind: pipeline
type: docker
name: default

steps:
  - name: checkout
    image: alpine:latest
    commands:
      - apk add --no-cache git
      - git clone https://github.com/Bparsons0904/postgres.git .

  - name: deploy_staging
    image: docker/compose:1.29.2
    environment:
      STAGING_DB_USER:
        from_secret: staging_db_user
      STAGING_DB_PASSWORD:
        from_secret: staging_db_password
      STAGING_DB_NAME:
        from_secret: staging_db_name
    commands:
      - cp -r ./staging/* ./ # Ensure the staging configuration files are in the correct directory
      - docker-compose stop postgres_staging
      - docker-compose rm -f postgres_staging
      - docker-compose up -d postgres_staging
      - docker image prune -f
    when:
      branch:
        - main

  - name: deploy_production
    image: docker/compose:1.29.2
    environment:
      PROD_DB_USER:
        from_secret: prod_db_user
      PROD_DB_PASSWORD:
        from_secret: prod_db_password
      PROD_DB_NAME:
        from_secret: prod_db_name
    commands:
      - cp -r ./production/* ./ # Ensure the production configuration files are in the correct directory
      - docker-compose stop postgres_production
      - docker-compose rm -f postgres_production
      - docker-compose up -d postgres_production
      - docker image prune -f
    when:
      event:
        - tag
      ref:
        - refs/tags/v*
