kind: pipeline
type: docker
name: default
steps:
  - name: build_postgres_image
    image: docker:20.10.7
    commands:
      - docker build -t custom-postgres:16.5 .
      - docker build -t postgres-exporter:latest -f Dockerfile.exporter .
  - name: deploy_staging
    image: docker/compose:1.29.2
    environment:
      STAGING_DB_USER:
        from_secret: staging_db_user
      STAGING_DB_PASSWORD:
        from_secret: staging_db_password
      STAGING_DB_NAME:
        from_secret: staging_db_name
    commands:
      - docker-compose stop postgres_staging postgres_exporter_staging
      - docker-compose rm -f postgres_staging postgres_exporter_staging
      - docker-compose up -d postgres_staging postgres_exporter_staging
    when:
      branch:
        - main
  - name: deploy_production
    image: docker/compose:1.29.2
    environment:
      PROD_DB_USER:
        from_secret: prod_db_user
      PROD_DB_PASSWORD:
        from_secret: prod_db_password
      PROD_DB_NAME:
        from_secret: prod_db_name
    commands:
      - docker-compose stop postgres_production postgres_exporter_production
      - docker-compose rm -f postgres_production postgres_exporter_production
      - docker-compose up -d postgres_production postgres_exporter_production
      - docker image prune -f
    when:
      event:
        - tag
      ref:
        - refs/tags/v*
