kind: pipeline
type: docker
name: default

steps:
  - name: deploy_staging
    image: docker/compose:1.29.2
    environment:
      STAGING_DB_USER:
        from_secret: staging_db_user
      STAGING_DB_PASSWORD:
        from_secret: staging_db_password
      STAGING_DB_NAME:
        from_secret: staging_db_name
    commands:
      - envsubst < init_staging.sql > init_staging.sql
      - docker-compose stop postgres_staging
      - docker-compose rm -f postgres_staging
      - docker-compose up -d postgres_staging
      - docker image prune -f
    when:
      branch:
        - main

  - name: deploy_production
    image: docker/compose:1.29.2
    environment:
      PROD_DB_USER:
        from_secret: prod_db_user
      PROD_DB_PASSWORD:
        from_secret: prod_db_password
      PROD_DB_NAME:
        from_secret: prod_db_name
    commands:
      - envsubst < init_production.sql > init_production.sql
      - docker-compose stop postgres_production
      - docker-compose rm -f postgres_production
      - docker-compose up -d postgres_production
      - docker image prune -f
    when:
      event:
        - tag
      ref:
        - refs/tags/v*
