FROM prometheuscommunity/postgres-exporter:latest

USER root

RUN mkdir -p /etc/postgres_exporter/conf/ && \
  chown -R nobody:nobody /etc/postgres_exporter

COPY postgres_exporter_config/queries.yaml /etc/postgres_exporter/conf/queries.yaml
RUN chown nobody:nobody /etc/postgres_exporter/conf/queries.yaml

USER nobody
