services:
  postgres_staging:
    image: postgres:latest
    container_name: postgres_staging
    environment:
      POSTGRES_USER: ${STAGING_DB_USER}
      POSTGRES_PASSWORD: ${STAGING_DB_PASSWORD}
      POSTGRES_DB: ${STAGING_DB_NAME}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
      - ./staging/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./staging/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5080:5432"
    restart: unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  postgres_production:
    image: postgres:latest
    container_name: postgres_production
    environment:
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      POSTGRES_DB: ${PROD_DB_NAME}
    volumes:
      - postgres_production_data:/var/lib/postgresql/data
      - ./production/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./production/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5076:5432"
    restart: unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  postgres_staging_data:
  postgres_production_data:
