services:
  postgres_staging:
    build: .
    image: custom-postgres
    container_name: postgres_staging
    environment:
      POSTGRES_USER: ${STAGING_DB_USER}
      POSTGRES_PASSWORD: ${STAGING_DB_PASSWORD}
      POSTGRES_DB: ${STAGING_DB_NAME}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    ports:
      - "5080:5432"
    restart: unless-stopped

  postgres_production:
    build: .
    image: custom-postgres
    container_name: postgres_production
    environment:
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      POSTGRES_DB: ${PROD_DB_NAME}
    volumes:
      - postgres_production_data:/var/lib/postgresql/data
    ports:
      - "5076:5432"
    restart: unless-stopped

volumes:
  postgres_staging_data:
  postgres_production_data:
